function [] = plot_coil_field(coil_config,n)
%PLOT_COIL_FIELD Plots the superposition of the fields generated by the coils in array coils onto figure n

figure(n);

total_fields=zeros(size(coil_config.coils(1).fields_cartesian));
for i=1:1:length(coil_config.coils)
    total_fields=total_fields+coil_config.coils(i).fields_cartesian;
end

figure(1);
quiver3(coil_config.xs_plot,coil_config.ys_plot,coil_config.zs_plot,total_fields(:,1),total_fields(:,2),total_fields(:,3),...
    3,'Color',[0.4660 0.6740 0.1880]);
xlabel("x");
ylabel("y");
axis equal

end

